#!/bin/bash

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

ISSUE_NO_PATTERN="(#|[Ff][Oo][Rr][Cc][Ee]-|i)[0-9]{1,}"

get_branch_name() {
  BRANCH_NAME=`git branch | grep \* | awk '{print $2}'`
  if [[ $BRANCH_NAME =~ (i|i-d|feature\/|bugfix\/|hotfix\/|release\/|feat\/|fix\/|hfix\/|rel\/)[0-9]{1,} ]]; then
    echo "$BRANCH_NAME" | sed -e "s/^.*\(i\|i-d\|feature\/\|bugfix\/\|hotfix\/\|release\/\|feat\/\|fix\/\|hfix\/\|rel\/\)\([0-9]\+\).*$/\2/g"
  else
    echo ""
  fi
}

get_commit_message() {
  MSG=`cat ${COMMIT_MSG_FILE} | grep -v -e '^#' -e '^\s*$' | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g'`
  echo "${MSG}"
}

ISSUE_NO=`get_branch_name`
COMMIT_MSG=`get_commit_message`

if [ "${COMMIT_SOURCE}" = "" ] || [ ${COMMIT_SOURCE} = "message" ] || [ ${COMMIT_SOURCE} = "commit" ]; then
  if [ -n ${ISSUE_NO} ]; then
    if [[ ${COMMIT_MSG} =~ ${ISSUE_NO_PATTERN} ]]; then
      :
    else
      mv $COMMIT_MSG_FILE $COMMIT_MSG_FILE.tmp
      echo "i${ISSUE_NO} `cat $COMMIT_MSG_FILE.tmp`" > $COMMIT_MSG_FILE
    fi
  fi
fi